name: Build Windows on ARM64 Binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'arm64'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build EXE
      run: pyinstaller main.spec

    - name: Upload Windows ARM64 EXE
      uses: actions/upload-artifact@v4
      with:
        name: windows-arm64-exe
        path: dist/*.exe
